---
- name: "Install and configure Apache on Debian/Ubuntu"
  hosts: linux_servers
  become: yes
  gather_facts: false
  tasks:
    
    - handler: "Restart Apache"
      service:
        name: apache2
        state: restarted

    - name: "Install apache2"
      apt:
        name: apache2
        state: present
        update_cache: yes
        notify: "Restart Apache"

    - name: "Kijk of Apache2 aan staat"
      service:
        name: apache2
        state: started
        enabled: yes




